### ISSUE TITLE
Does this support classic 3.4.0?

### ISSUE THREAD

**Issue by lineagedr** [namreeb/dumpwow#11]
Hey, thanks for the tool. I've tested with 1.14.0 and it worked well but when unpacking 3.4.0 version it seemed still obfuscated.

**Comment by namreeb** [comment]
Can you be more specific?  The tool is not intended to deobfuscate per se.  It does not remove the opaque predicates, etc.  It only unpacks.  There is a chunk of packed code that gets unpacked at load time.  It also attempts to rebuild the import table.

**Comment by lineagedr** [comment]
Well, first I'd like to preface by saying that this is my first time doing any reverse engineering. My goal is to find the updateFields for 3.4.0. 

if I search for something like knownTitles I could find it in the unpacked 1.14.0 version
![image](https://github.com/namreeb/dumpwow/assets/12139798/c9773cd8-cc7e-47ce-9ffe-68f37f34da9c)

while in the unpacked 3.4.0 IDA doesn't find it.
